version: '3.8'

services:
  # PHP-FPM service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel

  # MySQL service
  mysql:
    image: "mysql/mysql-server:8.0"
    container_name: laravel_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - laravel

  # Nginx service
  web:
    image: nginx:alpine
    container_name: laravel_nginx
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
